/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  conceptsSidebar: [{ type: 'autogenerated', dirName: 'concepts' }],
  cardanoAmmSidebar: [{ type: 'autogenerated', dirName: 'cardano-amm' }],
  ergoAmmSidebar: [{ type: 'autogenerated', dirName: 'ergo-amm' }],
}

module.exports = sidebars
